// Generated by typings
// Source: typings/created/mapillary-js/mapillary-js.d.ts
declare namespace mapillaryjs {
  export interface Edge {
    data: any,
    from: string,
    to: string
  }

  export const EdgeDirection: any;

  export interface LatLon {
    lat: number;
    lon: number;
  }

  export interface Node {
    ca: any;
    key: string;
    latLon: LatLon;
    originalLatLon: LatLon;
    pano: boolean;
    sequenceEdges$: any;
    sequenceKey: string;
    spatialEdges$: any;
  }

  export const RenderMode: any;

  export interface SequenceEdges {
    edges: Edge[],
  }

  export interface SpatialEdges {
    edges: Edge[],
  }

  export class Viewer {
    constructor(viewerId: string, cliendId: string, imageKey: string, options?: any);
  }

  export const TagComponent: any;

}

declare module 'mapillary-js' {
  export = mapillaryjs;
}
